# Generated by Django 2.2.6 on 2020-01-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('special', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('nod', models.IntegerField(default=0)),
                ('maxd', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('ph', models.CharField(max_length=10, unique=True)),
                ('link', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('adhar_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('adhar_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.patient')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.ngo'),
        ),
        migrations.CreateModel(
            name='doregis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.doc')),
                ('evid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('eventid', 'adhar_no'), name='unique_desc'),
        ),
    ]
