# Generated by Django 2.2.6 on 2020-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
