# Generated by Django 2.2.6 on 2020-01-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_event_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='doregis',
            constraint=models.UniqueConstraint(fields=('evid', 'docid'), name='onedocforeve'),
        ),
    ]
