# Generated by Django 2.2.6 on 2020-01-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_auto_20200121_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(max_length=255, null=True, upload_to='pictures/'),
        ),
    ]
